# ==== CONFIGURE =====
# Use a Node 16 base image
FROM node:16-alpine

# FROM nginx:latest
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY . .
# ==== BUILD =====
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm ci 
# Build the app
RUN npm run build
# ==== RUN =======
# Set the env to "production"
ENV NODE_ENV production


CMD ["npm run serve"]